FROM centos:6.6
MAINTAINER Robert Grzelka <robert.grzelka@outlook.com>



RUN echo "######################### INSTALL STANDARD PACKAGES #########################"
RUN yum install -y git

ENV setup_dir /pintos/setup
ENV pintos_dir /pintos


VOLUME [$pintos_dir]


RUN echo "######################### COPY GIT PINTOS TO USER #########################"

RUN git clone https://github.com/robgrzel/PintOS/ /tmp/

RUN mv /tmp/PintOS/* /pintos

env PATH $setup_dir/pintos-utils/:$PATH