FROM centos:6.6
MAINTAINER Robert Grzelka <robert.grzelka@outlook.com>
#BASED ON: https://github.com/yhpark/dockerfile-pintos-kaist
#...https://github.com/JohnStarich/docker-pintos/blob/master/Dockerfile
#...https://hub.docker.com/r/hangpark/pintos-dev-env-kaist/
#run it with:
#docker run -d -p 3522:22 -p 7575:7575 -p 9595:9595 -h dev --privileged --security-opt seccomp:unconfined -e DISPLAY=$DISPLAY --name pintos-container --dns=8.8.8.8 -v  E:\PintOS\workspace:/home/pintos/workspace -P ubuntu-pintos-ssh 

### INFO
#this file is meant to build remotely
###


RUN yum install -y compat-gcc-34 compat-gcc-34-c++ \
					tar patch ncurses-devel ncurses\
					git compat-glibc-headers \
					perl gdb libGL SDL libaio alsa-lib\ 
					bluez-libs celt051 esound-libs gnutls \
					libjpeg-turbo pixman libpng pulseaudio-libs\
					spice-server xpra rox-filer openssh-server \
					pwgen xserver-xephyr xdm fluxbox xvfb sudo \
					firefox xterm openssh-server cmake \
					build-essential vim python tcpdump telnet byacc \
					flex iproute2 gdbserver less bison valgrind firefox

RUN ln /usr/bin/gcc34 /usr/bin/gcc
RUN ln /usr/bin/g++34 /usr/bin/g++

RUN cp -r /usr/lib/x86_64-redhat-linux5E/include/* /usr/local/include/			
			

#################################### ssh SETTINGS #########################

RUN mkdir -p /var/run/sshd ; chmod -rx /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
#RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd


ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN  /etc/init.d/sshd start


EXPOSE 22 9595 7575
			
#################################### PINTOS SETTINGS #########################


#write env variables
ENV user pintos
ENV setup_dir /home/pintos/setup
ENV home_dir /home/pintos
ENV pintos_dir /home/pintos

#create volume that will appear at runtime mounted
VOLUME [$pintos_dir]

RUN useradd -m -d $home_dir -s /bin/bash pintos
RUN echo -e '1\n1' | passwd pintos --stdin
RUN usermod -aG wheel pintos #as ubuntu : sudo adduser pintos sudo
RUN mkdir -p $pintos_dir
RUN mkdir -p $setup_dir

#if clone from github
#RUN git clone https://github.com/robgrzel/PintOS /tmp/$pintos_dir
#RUN mv /tmp/pintos/* $pintos_dir
#RUN ls -la
#RUN mv /PintOS/* $pintos_dir

WORKDIR $setup_dir

ADD setup $setup_dir
ADD pintos $pintos_dir/pintos
ADD pintos-misc $setup_dir/pintos/src/misc/

#deal with bug made in here https://registry.hub.docker.com/u/yhpark/pintos-kaist/
#where as in lab0 to run "pintos -- run alarm-multiple" from dir "pintos/src/threads"
#you would have to run "../utils/pintos -- run alarm-multiple"...:
ADD pintos-utils $setup_dir/pintos-utils/
#RUN mkdir -p $pintos_dir/pintos/src/utils/
RUN cp -rn $setup_dir/pintos-utils/* $pintos_dir/pintos/src/utils/

RUN ls -la $pintos_dir
RUN ls -la $setup_dir

RUN chmod -R 777 $pintos_dir

RUN SRCDIR=$setup_dir DSTDIR=/usr/ PINTOSDIR=$setup_dir/pintos $setup_dir/pintos/src/misc/bochs-2.2.6-build.sh
RUN rpm -i $setup_dir/qemu-img-0.15.0-1.el6.rfx.x86_64.rpm
RUN rpm -i $setup_dir/qemu-0.15.0-1.el6.rfx.x86_64.rpm

WORKDIR $pintos_dir/pintos/src/utils/

RUN make

USER pintos
WORKDIR $home_dir


RUN echo PATH=$pintos_dir/pintos/src/utils/:$PATH >> .profile


USER root
WORKDIR /

CMD ["/usr/sbin/sshd", "-D"]

